### ISSUE TITLE
issue with CoreOS flow

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang-content#115]
Command failed java.lang.RuntimeException: Slang Error : Error running: 'clear_docker_dangling_images_flow'.
    Error binding output: 'dangling_images_list_safe_to_delete',
    Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
    Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line numbe
r 1

StackTrace : 
Caused by: Traceback (most recent call last):
  File "<script>", line 1, in <module>
NameError: name 'images_list_safe_to_delete' is not defined

	at org.python.core.Py.NameError(Py.java:256)
	at org.python.core.PyFrame.getname(PyFrame.java:257)
	at org.python.pycode._pyx4797.f$0(<script>:1)
	at org.python.pycode._pyx4797.call_function(<script>)
	at org.python.core.PyTableCode.call(PyTableCode.java:166)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1312)
	at org.python.core.__builtin__.eval(__builtin__.java:483)
	at org.python.core.__builtin__.eval(__builtin__.java:487)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:214)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
	... 18 more
2015-04-22 14:09:24:957 4091331 [WorkerExecutionThread-8_101600053] ERROR io.cloudslang.worker.execution.reflection.ReflectionAdapterImpl  - Failed to run the action! Class: io.cloudslang.lang.runtime.navigations.Navigations, method: navigate, reason: Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.cloudslang.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:62)
	at io.cloudslang.worker.execution.services.ExecutionServiceImpl.navigate(ExecutionServiceImpl.java:355)
	at io.cloudslang.worker.execution.services.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:80)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:147)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.cloudslang.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1
	at io.cloudslang.lang.runtime.navigations.Navigations.navigate(Navigations.java:44)
	... 14 more
2015-04-22 14:09:24:958 4091332 [WorkerExecutionThread-8_101600053] ERROR io.cloudslang.worker.execution.services.ExecutionServiceImpl  - Error occurred during navigation execution. Execution id: 101600053
io.cloudslang.score.exceptions.FlowExecutionException: Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1
	at io.cloudslang.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:73)
	at io.cloudslang.worker.execution.services.ExecutionServiceImpl.navigate(ExecutionServiceImpl.java:355)
	at io.cloudslang.worker.execution.services.ExecutionServiceImpl.execute(ExecutionServiceImpl.java:80)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.executeRegularStep(SimpleExecutionRunnable.java:147)
	at io.cloudslang.worker.management.services.SimpleExecutionRunnable.run(SimpleExecutionRunnable.java:111)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at io.cloudslang.worker.management.services.WorkerThreadFactory$1.run(WorkerThreadFactory.java:33)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.cloudslang.worker.execution.reflection.ReflectionAdapterImpl.executeControlAction(ReflectionAdapterImpl.java:62)
	... 10 more
Caused by: java.lang.RuntimeException: Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1
	at io.cloudslang.lang.runtime.navigations.Navigations.navigate(Navigations.java:44)
	... 14 more
2015-04-22 14:09:24:958 4091332 [WorkerExecutionThread-8_101600053] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: SCORE_ERROR_EVENT Data is: {error_message=Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1, systemContext={executionIdContext=101600053, FLOW_TERMINATION_TYPE=SYSTEM_FAILURE, BEGIN_STEPS_MAP={io.cloudslang.base.strings.string_equals=1, io.cloudslang.docker.maintenance.diskspace_health_check=1, io.cloudslang.coreos.list_machines_public_ip=1, io.cloudslang.docker.images.get_used_images_flow=1, io.cloudslang.docker.utils.parse_inspect_for_parent=1, io.cloudslang.coreos.list_machines_id=1, io.cloudslang.docker.images.inspect_image=1, io.cloudslang.docker.images.clear_unused_docker_images=1, io.cloudslang.docker.images.get_dangling_images=1, io.cloudslang.docker.maintenance.docker_images_maintenance=1, io.cloudslang.base.lists.subtract_sets=1, io.cloudslang.docker.images.get_image_name_from_id=1, io.cloudslang.docker.images.clear_docker_images=1, io.cloudslang.docker.images.clear_docker_images_flow=1, io.cloudslang.docker.images.get_all_images=1, io.cloudslang.coreos.get_machine_public_ip=1, io.cloudslang.docker.images.get_used_images=1, io.cloudslang.coreos.cluster_docker_images_maintenance=1, io.cloudslang.base.os.linux.validate_linux_machine_ssh_access=1, io.cloudslang.docker.images.clear_docker_dangling_images_flow=1, io.cloudslang.docker.images.get_image_parent=1, io.cloudslang.base.comparisons.less_than_percentage=1, io.cloudslang.base.os.linux.check_linux_disk_space=1}, SCORE_EVENTS_QUEUE=[io.cloudslang.score.events.ScoreEvent@59e59219, io.cloudslang.score.events.ScoreEvent@2598bf99], RUNNING_PLANS_MAP={io.cloudslang.base.strings.string_equals=100000001, io.cloudslang.docker.maintenance.diskspace_health_check=100000002, io.cloudslang.coreos.list_machines_public_ip=100000003, io.cloudslang.docker.images.get_used_images_flow=100000004, io.cloudslang.docker.utils.parse_inspect_for_parent=100000005, io.cloudslang.coreos.list_machines_id=100000006, io.cloudslang.docker.images.inspect_image=100000007, io.cloudslang.docker.images.clear_unused_docker_images=100000008, io.cloudslang.docker.images.get_dangling_images=100000009, io.cloudslang.docker.maintenance.docker_images_maintenance=100000010, io.cloudslang.base.lists.subtract_sets=100000011, io.cloudslang.docker.images.get_image_name_from_id=100000012, io.cloudslang.docker.images.clear_docker_images=100000013, io.cloudslang.docker.images.clear_docker_images_flow=100000014, io.cloudslang.docker.images.get_all_images=100000015, io.cloudslang.coreos.get_machine_public_ip=100000016, io.cloudslang.docker.images.get_used_images=100000017, io.cloudslang.coreos.cluster_docker_images_maintenance=100000023, io.cloudslang.base.os.linux.validate_linux_machine_ssh_access=100000018, io.cloudslang.docker.images.clear_docker_dangling_images_flow=100000019, io.cloudslang.docker.images.get_image_parent=100000020, io.cloudslang.base.comparisons.less_than_percentage=100000021, io.cloudslang.base.os.linux.check_linux_disk_space=100000022}, EXECUTION_STEP_ERROR_KEY=Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1}, logMessage=Error occurred during navigation execution , SCORE_ERROR_TYPE=STEP_NAV_ERROR}
2015-04-22 14:09:24:958 4091332 [WorkerExecutionThread-8_101600053] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: EVENT_OUTPUT_START Data is: {PATH=0/3/0/2/0/2/0, DESCRIPTION=Output binding started, EXECUTIONID=101600053, executableResults=[io.cloudslang.lang.entities.bindings.Result@45ce9de2[name=SUCCESS,expression=<null>], io.cloudslang.lang.entities.bindings.Result@11a8875[name=FAILURE,expression=<null>]], TIMESTAMP=Wed Apr 22 14:09:24 IDT 2015, executableOutputs=[io.cloudslang.lang.entities.bindings.Output@749ab715[name=dangling_images_list_safe_to_delete,expression=images_list_safe_to_delete], io.cloudslang.lang.entities.bindings.Output@149eaa68[name=amount_of_dangling_images_deleted,expression=0 if images_list_safe_to_delete == '' else amount_of_dangling_images]], actionReturnValues=ReturnValues{result='FAILURE', outputs={private_key_file=C:\Users\wahnonm\.ssh\id_rsa, docker_password=, used_images=busybox:latest , docker_host=188.166.104.156, docker_username=core, timeout=6000000}}, TYPE=EVENT_OUTPUT_START, EXECUTABLE_NAME=clear_docker_dangling_images_flow}
2015-04-22 14:09:24:958 4091332 [WorkerExecutionThread-8_101600053] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: SLANG_EXECUTION_EXCEPTION Data is: {PATH=0/3/0/2/0/2/0, DESCRIPTION=Error detected during step, EXECUTIONID=101600053, TIMESTAMP=Wed Apr 22 14:09:24 IDT 2015, EXCEPTION=Error running: 'clear_docker_dangling_images_flow'.
	Error binding output: 'dangling_images_list_safe_to_delete',
	Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
	Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in <script> at line number 1, TYPE=SLANG_EXECUTION_EXCEPTION}
2015-04-22 14:09:24:965 4091339 [scoreWorkerScheduler-2] INFO  io.cloudslang.lang.cli.SlangCLI  - Event received: SCORE_FINISHED_EVENT Data is: {IS_BRANCH=false, executionIdContext=101600053, systemContext=io.cloudslang.score.lang.SystemContext@a81aa74a, EXECUTION_CONTEXT={userInputs={}, runEnv=io.cloudslang.lang.runtime.env.RunEnvironment@646a028d}}

**Comment by meirwah** [comment]
@Bonczidai @orius123  this is the serlization issue...

**Comment by meirwah** [comment]
closing this, and moving the CloudSlang, ince it is serlization issue...
